### ISSUE TITLE
Cannot find module '@lavamoat/mpc-ecdsa-wasm'

### ISSUE THREAD

**Issue by luca992** [LavaMoat/tss-snap#108]
I'm attempting to use the js library in a test and I can't figure out why the `@lavamoat/mpc-ecdsa-wasm` module can't be found at runtime.

```
mocha --require ts-node/register --timeout 60000 *.test.ts

Error: Cannot find module '@lavamoat/mpc-ecdsa-wasm'
```

 Does it not support running in a node environment? Or would only browser environments work?

**Comment by tmpfs** [comment]
Hi @luca992,

Currently this compiles to webassembly and targets the browser - it has not been tested in nodejs.

Furthermore, this project can be considered deprecated, work is now moving to a CGGMP implementation [here](https://github.com/mpc-sdk/framework/) and the underlying [multi-party-ecdsa](https://github.com/ZenGo-X/multi-party-ecdsa) code is no longer maintained so you should not use this in production.

We will maintain a fork for the CGGMP work in progress.

Hope that helps 🙏

**Comment by luca992** [comment]
Got it. Thanks for the info! I was planning on using gg20 for what I'm building first as I hadn't found many working cggmp libraries. Then trying to port over to cggmp when I found something working.

Quick unrelated question does cggmp also allow all signing rounds besides the last to be preprocessed without communication with the other parties?

**Comment by tmpfs** [comment]
Cool, yes CGGMP supports pre-signatures, however they must be handled with care otherwise you can leak the private key.

**Comment by luca992** [comment]
I got it to load in nodejs. I'm not exactly sure why, but I had to change the `package.json` from 

```
{
  "name": "@lavamoat/mpc-ecdsa-wasm",
  "description": "Webassembly bindings to multi-party-ecdsa",
  "version": "0.2.1",
  "license": "MIT",
  "files": [
    "snippets/",
    "mpc_ecdsa_wasm_bg.wasm",
    "mpc_ecdsa_wasm.js",
    "mpc_ecdsa_wasm.d.ts"
  ],
  "module": "mpc_ecdsa_wasm.js",
  "types": "mpc_ecdsa_wasm.d.ts",
  "sideEffects": false
}
```

to:

```
{
  "name": "@lavamoat/mpc-ecdsa-wasm",
  "description": "Webassembly bindings to multi-party-ecdsa",
  "version": "0.2.1",
  "license": "MIT",
  "files": [
    "snippets/",
    "mpc_ecdsa_wasm_bg.wasm",
    "mpc_ecdsa_wasm.js",
    "mpc_ecdsa_wasm.d.ts"
  ],
  "main": "mpc_ecdsa_wasm.js",
  "types": "mpc_ecdsa_wasm.d.ts",
  "type": "module",
  "sideEffects": false
}
```

Then using [happy-dom](https://github.com/capricorn86/happy-dom) to work around the browser requirements seems to work:

```

import {GlobalRegistrator} from "@happy-dom/global-registrator";
import * as fs from "fs";


async function main() {
    GlobalRegistrator.register()
    let wasmPath = `${process.cwd()}/node_modules/mpc-ecdsa-wasm/mpc_ecdsa_wasm_bg.wasm`
    console.log(`Trying to get wasm at: ${wasmPath}`);
    let wasmBuffer = fs.readFileSync(wasmPath);
    await (await import("mpc-ecdsa-wasm")).default(wasmBuffer);
}

main();
```

**Comment by tmpfs** [comment]
Nice one, bear in mind that file is automatically generated by `wasm-pack`.

Note also that my build process targets the browser with `wasm-pack --target web` so just compiling with `--target node` might get what you need.

**Comment by luca992** [comment]
@tmpfs thanks for the tip! You're right.

```
wasm:
	@cd packages/wasm && wasm-pack build --target nodejs --scope lavamoat
```
Works great. And I don't have to use any browser hacks with happydom

**Comment by tmpfs** [comment]
Cool @luca992, glad you got it sorted!

**Comment by luca992** [comment]
> Hi @luca992,
> 
> Currently this compiles to webassembly and targets the browser - it has not been tested in nodejs.
> 
> Furthermore, this project can be considered deprecated, work is now moving to a CGGMP implementation [here](https://github.com/mpc-sdk/framework/) and the underlying [multi-party-ecdsa](https://github.com/ZenGo-X/multi-party-ecdsa) code is no longer maintained so you should not use this in production.
> 
> We will maintain a fork for the CGGMP work in progress.
> 
> Hope that helps 🙏

is there a working branch with CGGMP atm?
