### ISSUE TITLE
Optimize the performance of the wasm version of the multi-party-ecdsa library

### ISSUE THREAD

**Issue by 12915494174** [LavaMoat/tss-snap#93]
Hello, I found that after I converted the multi-party-ecdsa library to wasm, its performance dropped by more than ten times. Do you have any good methods to further improve its performance? I tried to use the automatic vectorization of rust to optimize the performance. Perhaps it was a problem of operation. I did not make substantive progress.

**Comment by tmpfs** [comment]
You should raise this in the relevant upstream repository if performance is a problem for you.
